# This role is mainly for jenkins to dynamically create inventory files
# Currently in use for Ansible provisioning using install from scratch method (Single node and Multi Node)
# This is working but can be improved greatly.. if anyone has a better idea.. - Bryan

- block:
    - command: cp jenkins-hosts.template jenkins-hosts creates=jenkins-hosts

    - replace: dest=./jenkins-hosts regexp='@db_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "db"

    - replace: dest=./jenkins-hosts regexp='@admin_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "admin"

  when: multinode == 'false'

- block:
    - command: cp jenkins-hosts-multi.template jenkins-hosts creates=jenkins-hosts

    - replace: dest=./jenkins-hosts regexp='@db_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "db"

    - replace: dest=./jenkins-hosts regexp='@admin_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "admin"

    - replace: dest=./jenkins-hosts regexp='@soa_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "soa"

    - replace: dest=./jenkins-hosts regexp='@bpm_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "bpm"

    - replace: dest=./jenkins-hosts regexp='@b2b_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "b2b"

    - replace: dest=./jenkins-hosts regexp='@ess_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "ess"

    - replace: dest=./jenkins-hosts regexp='@bam_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "bam"

    - replace: dest=./jenkins-hosts regexp='@osb_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "osb"  

    - replace: dest=./jenkins-hosts regexp='@soa_host@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "mft"

    - replace: dest=./jenkins-hosts regexp='@soa_host_1_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "soahost1server"

    - replace: dest=./jenkins-hosts regexp='@soa_host_2_ip@' replace={{ ec2["instances"][0]["private_ip"] }}
      when: type == "soahost2server"

  when: multinode == 'true'


- replace: dest=./jenkins-hosts regexp='@env@' replace={{ env }}
